#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doorprize
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_DOORPIZE")]
	public partial class DoorprizeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_DATA_UNDI(TBL_T_DATA_UNDI instance);
    partial void UpdateTBL_T_DATA_UNDI(TBL_T_DATA_UNDI instance);
    partial void DeleteTBL_T_DATA_UNDI(TBL_T_DATA_UNDI instance);
    partial void InsertTBL_M_HADIAH(TBL_M_HADIAH instance);
    partial void UpdateTBL_M_HADIAH(TBL_M_HADIAH instance);
    partial void DeleteTBL_M_HADIAH(TBL_M_HADIAH instance);
    partial void InsertTBL_T_PEMENANG(TBL_T_PEMENANG instance);
    partial void UpdateTBL_T_PEMENANG(TBL_T_PEMENANG instance);
    partial void DeleteTBL_T_PEMENANG(TBL_T_PEMENANG instance);
    partial void InsertTBL_T_RAW_DATA(TBL_T_RAW_DATA instance);
    partial void UpdateTBL_T_RAW_DATA(TBL_T_RAW_DATA instance);
    partial void DeleteTBL_T_RAW_DATA(TBL_T_RAW_DATA instance);
    #endregion
		
		public DoorprizeDataContext() : 
				base(global::Doorprize.Properties.Settings.Default.DB_DOORPIZEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DoorprizeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoorprizeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoorprizeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DoorprizeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_T_DATA_UNDI> TBL_T_DATA_UNDIs
		{
			get
			{
				return this.GetTable<TBL_T_DATA_UNDI>();
			}
		}
		
		public System.Data.Linq.Table<VW_DATA_UNDI> VW_DATA_UNDIs
		{
			get
			{
				return this.GetTable<VW_DATA_UNDI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_M_HADIAH> TBL_M_HADIAHs
		{
			get
			{
				return this.GetTable<TBL_M_HADIAH>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_PEMENANG> TBL_T_PEMENANGs
		{
			get
			{
				return this.GetTable<TBL_T_PEMENANG>();
			}
		}
		
		public System.Data.Linq.Table<VW_DATA_PEMENANG> VW_DATA_PEMENANGs
		{
			get
			{
				return this.GetTable<VW_DATA_PEMENANG>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_RAW_DATA> TBL_T_RAW_DATAs
		{
			get
			{
				return this.GetTable<TBL_T_RAW_DATA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_DATA_UNDI")]
	public partial class TBL_T_DATA_UNDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PID;
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _DEPT;
		
		private string _JABATAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIDChanging(System.Guid value);
    partial void OnPIDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnDEPTChanging(string value);
    partial void OnDEPTChanged();
    partial void OnJABATANChanging(string value);
    partial void OnJABATANChanged();
    #endregion
		
		public TBL_T_DATA_UNDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this.OnDEPTChanging(value);
					this.SendPropertyChanging();
					this._DEPT = value;
					this.SendPropertyChanged("DEPT");
					this.OnDEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="VarChar(50)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this.OnJABATANChanging(value);
					this.SendPropertyChanging();
					this._JABATAN = value;
					this.SendPropertyChanged("JABATAN");
					this.OnJABATANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DATA_UNDI")]
	public partial class VW_DATA_UNDI
	{
		
		private System.Guid _PID;
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _DEPT;
		
		private string _JABATAN;
		
		private System.Nullable<int> _STATUS_UNID;
		
		public VW_DATA_UNDI()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this._PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="VarChar(50)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this._JABATAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_UNID", DbType="Int")]
		public System.Nullable<int> STATUS_UNID
		{
			get
			{
				return this._STATUS_UNID;
			}
			set
			{
				if ((this._STATUS_UNID != value))
				{
					this._STATUS_UNID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_M_HADIAH")]
	public partial class TBL_M_HADIAH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PID;
		
		private string _HADIAH;
		
		private System.Nullable<int> _QTY;
		
		private System.Nullable<int> _QTY_PEMENANG;
		
		private System.Nullable<int> _STATUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIDChanging(System.Guid value);
    partial void OnPIDChanged();
    partial void OnHADIAHChanging(string value);
    partial void OnHADIAHChanged();
    partial void OnQTYChanging(System.Nullable<int> value);
    partial void OnQTYChanged();
    partial void OnQTY_PEMENANGChanging(System.Nullable<int> value);
    partial void OnQTY_PEMENANGChanged();
    partial void OnSTATUSChanging(System.Nullable<int> value);
    partial void OnSTATUSChanged();
    #endregion
		
		public TBL_M_HADIAH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HADIAH", DbType="VarChar(50)")]
		public string HADIAH
		{
			get
			{
				return this._HADIAH;
			}
			set
			{
				if ((this._HADIAH != value))
				{
					this.OnHADIAHChanging(value);
					this.SendPropertyChanging();
					this._HADIAH = value;
					this.SendPropertyChanged("HADIAH");
					this.OnHADIAHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int")]
		public System.Nullable<int> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_PEMENANG", DbType="Int")]
		public System.Nullable<int> QTY_PEMENANG
		{
			get
			{
				return this._QTY_PEMENANG;
			}
			set
			{
				if ((this._QTY_PEMENANG != value))
				{
					this.OnQTY_PEMENANGChanging(value);
					this.SendPropertyChanging();
					this._QTY_PEMENANG = value;
					this.SendPropertyChanged("QTY_PEMENANG");
					this.OnQTY_PEMENANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Int")]
		public System.Nullable<int> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_PEMENANG")]
	public partial class TBL_T_PEMENANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PID;
		
		private string _PID_HADIAH;
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _DEPT;
		
		private string _JABATAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIDChanging(string value);
    partial void OnPIDChanged();
    partial void OnPID_HADIAHChanging(string value);
    partial void OnPID_HADIAHChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnNAMAChanging(string value);
    partial void OnNAMAChanged();
    partial void OnDEPTChanging(string value);
    partial void OnDEPTChanged();
    partial void OnJABATANChanging(string value);
    partial void OnJABATANChanged();
    #endregion
		
		public TBL_T_PEMENANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID_HADIAH", DbType="VarChar(50)")]
		public string PID_HADIAH
		{
			get
			{
				return this._PID_HADIAH;
			}
			set
			{
				if ((this._PID_HADIAH != value))
				{
					this.OnPID_HADIAHChanging(value);
					this.SendPropertyChanging();
					this._PID_HADIAH = value;
					this.SendPropertyChanged("PID_HADIAH");
					this.OnPID_HADIAHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this.OnNAMAChanging(value);
					this.SendPropertyChanging();
					this._NAMA = value;
					this.SendPropertyChanged("NAMA");
					this.OnNAMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this.OnDEPTChanging(value);
					this.SendPropertyChanging();
					this._DEPT = value;
					this.SendPropertyChanged("DEPT");
					this.OnDEPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="VarChar(50)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this.OnJABATANChanging(value);
					this.SendPropertyChanging();
					this._JABATAN = value;
					this.SendPropertyChanged("JABATAN");
					this.OnJABATANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_DATA_PEMENANG")]
	public partial class VW_DATA_PEMENANG
	{
		
		private string _HADIAH;
		
		private string _NRP;
		
		private string _NAMA;
		
		private string _DEPT;
		
		private string _JABATAN;
		
		public VW_DATA_PEMENANG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HADIAH", DbType="VarChar(50)")]
		public string HADIAH
		{
			get
			{
				return this._HADIAH;
			}
			set
			{
				if ((this._HADIAH != value))
				{
					this._HADIAH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(50)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT", DbType="VarChar(50)")]
		public string DEPT
		{
			get
			{
				return this._DEPT;
			}
			set
			{
				if ((this._DEPT != value))
				{
					this._DEPT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JABATAN", DbType="VarChar(50)")]
		public string JABATAN
		{
			get
			{
				return this._JABATAN;
			}
			set
			{
				if ((this._JABATAN != value))
				{
					this._JABATAN = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_RAW_DATA")]
	public partial class TBL_T_RAW_DATA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _PID;
		
		private string _BARCODE;
		
		private string _NAME;
		
		private string _TELEPHONE;
		
		private string _COMPANY;
		
		private string _JOB_TITLE;
		
		private string _EMAIL;
		
		private string _VIP;
		
		private string _SESSION;
		
		private string _NOTES;
		
		private string _LOCATION;
		
		private System.Nullable<int> _QUANTITY;
		
		private System.Nullable<System.DateTime> _DATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPIDChanging(System.Guid value);
    partial void OnPIDChanged();
    partial void OnBARCODEChanging(string value);
    partial void OnBARCODEChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnTELEPHONEChanging(string value);
    partial void OnTELEPHONEChanged();
    partial void OnCOMPANYChanging(string value);
    partial void OnCOMPANYChanged();
    partial void OnJOB_TITLEChanging(string value);
    partial void OnJOB_TITLEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnVIPChanging(string value);
    partial void OnVIPChanged();
    partial void OnSESSIONChanging(string value);
    partial void OnSESSIONChanged();
    partial void OnNOTESChanging(string value);
    partial void OnNOTESChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnQUANTITYChanging(System.Nullable<int> value);
    partial void OnQUANTITYChanged();
    partial void OnDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnDATEChanged();
    #endregion
		
		public TBL_T_RAW_DATA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid PID
		{
			get
			{
				return this._PID;
			}
			set
			{
				if ((this._PID != value))
				{
					this.OnPIDChanging(value);
					this.SendPropertyChanging();
					this._PID = value;
					this.SendPropertyChanged("PID");
					this.OnPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARCODE", DbType="VarChar(50)")]
		public string BARCODE
		{
			get
			{
				return this._BARCODE;
			}
			set
			{
				if ((this._BARCODE != value))
				{
					this.OnBARCODEChanging(value);
					this.SendPropertyChanging();
					this._BARCODE = value;
					this.SendPropertyChanged("BARCODE");
					this.OnBARCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(50)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEPHONE", DbType="VarChar(50)")]
		public string TELEPHONE
		{
			get
			{
				return this._TELEPHONE;
			}
			set
			{
				if ((this._TELEPHONE != value))
				{
					this.OnTELEPHONEChanging(value);
					this.SendPropertyChanging();
					this._TELEPHONE = value;
					this.SendPropertyChanged("TELEPHONE");
					this.OnTELEPHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="VarChar(50)")]
		public string COMPANY
		{
			get
			{
				return this._COMPANY;
			}
			set
			{
				if ((this._COMPANY != value))
				{
					this.OnCOMPANYChanging(value);
					this.SendPropertyChanging();
					this._COMPANY = value;
					this.SendPropertyChanged("COMPANY");
					this.OnCOMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOB_TITLE", DbType="VarChar(50)")]
		public string JOB_TITLE
		{
			get
			{
				return this._JOB_TITLE;
			}
			set
			{
				if ((this._JOB_TITLE != value))
				{
					this.OnJOB_TITLEChanging(value);
					this.SendPropertyChanging();
					this._JOB_TITLE = value;
					this.SendPropertyChanged("JOB_TITLE");
					this.OnJOB_TITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIP", DbType="VarChar(50)")]
		public string VIP
		{
			get
			{
				return this._VIP;
			}
			set
			{
				if ((this._VIP != value))
				{
					this.OnVIPChanging(value);
					this.SendPropertyChanging();
					this._VIP = value;
					this.SendPropertyChanged("VIP");
					this.OnVIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSION", DbType="VarChar(50)")]
		public string SESSION
		{
			get
			{
				return this._SESSION;
			}
			set
			{
				if ((this._SESSION != value))
				{
					this.OnSESSIONChanging(value);
					this.SendPropertyChanging();
					this._SESSION = value;
					this.SendPropertyChanged("SESSION");
					this.OnSESSIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTES", DbType="VarChar(50)")]
		public string NOTES
		{
			get
			{
				return this._NOTES;
			}
			set
			{
				if ((this._NOTES != value))
				{
					this.OnNOTESChanging(value);
					this.SendPropertyChanging();
					this._NOTES = value;
					this.SendPropertyChanged("NOTES");
					this.OnNOTESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="VarChar(50)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Int")]
		public System.Nullable<int> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this.OnQUANTITYChanging(value);
					this.SendPropertyChanging();
					this._QUANTITY = value;
					this.SendPropertyChanged("QUANTITY");
					this.OnQUANTITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
